apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.3
    helm:
      valueFiles:
      - $values/apps/external-secrets/values.yaml
  - repoURL: https://github.com/nabhanxyz/argocd.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).   
    syncOptions:
    - CreateNamespace=true
