global:
  enabled: true
  namespace: vault
injector:
  enabled: true

server:
  ha:
    enabled: true
    raft:
      enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - host: vault.nabhan.xyz

ui:
  enabled: true


