global:
  enabled: true
  namespace: vault
injector:
  enabled: true

server:
  ha:
    enabled: true
    raft:
      enabled: true

ui:
  enabled: true

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
  - host: vault.nabhan.xyz
