redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1

applicationSet:
  replicaCount: 1

crds:
  # -- Install and upgrade CRDs
  install: true

configs:
  cm:
    accounts.mike: apikey, login
  rbac:
    policy.csv: |
      g, mike, role:admin
