global:
  domain: argocd.nabhan.xyz

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1

applicationSet:
  replicaCount: 1

crds:
  # -- Install and upgrade CRDs
  install: true

configs:
  cm:
    accounts.mike: apikey, login
    server.insecure: "true"
  rbac:
    policy.csv: |
      g, mike, role:admin
